---
title: "Example 01: Get up and running"
---

We will be working with the most recent stable versions of R and RStudio, as well as with a number of additional packages. You will need to install R, RStudio, and the necessary packages on your own computer.

### 1. Install R on your computer

Begin by installing R (<http://cloud.r-project.org>). Choose the version appropriate for your computing platform: 


- If you use macOS with an Apple Silicon processor (i.e. an M1, M2, or M3 chip), then install [R for macOS's Apple Silicon build](https://cran.r-project.org/bin/macosx/big-sur-arm64/base/R-4.3.2-arm64.pkg). This version does not work on older, Intel-based Macs.

- If you use macOS with an Intel processor, then install [R for macOS's Intel build](https://cran.r-project.org/bin/macosx/big-sur-x86_64/base/R-4.3.2-x86_64.pkg). 

- If you use Microsoft Windows, then install [R for Windows](https://cran.r-project.org/bin/windows/base/R-4.3.2-win.exe).

- If you use Linux, [choose a distribution](https://cloud.r-project.org/bin/linux/) and install it.

### 2. Install RStudio on your computer

- If you use macOS (whether Apple Silicon or Intel), [install this version of RStudio](https://download1.rstudio.org/electron/macos/RStudio-2023.12.0-369.dmg).

- If you use Windows, [install this version of RStudio](https://download1.rstudio.org/electron/windows/RStudio-2023.12.0-369.exe).

- If you use Linux, [choose your distribution from the download page](https://posit.co/download/rstudio-desktop/).

### 3. Installing some additional packages

- Once R and RStudio are installed, launch RStudio. Either carefully type in or copy-and-paste the following lines of code at R’s command prompt, located in the RStudio window named “Console”, and then hit return. To copy this chunk of code, mouse over the code click the clipboard icon, {{< fa clipboard >}}, that appears in the top right corner of the chunk.


```{r, eval=FALSE, echo=TRUE}

course_packages <- c("tidyverse", "babynames", "broom",
    "drat", "gapminder", "here", "janitor", "naniar", 
    "palmerpenguins", "skimr", "slider", "socviz",
    "usethis", "visdat","reprex")

install.packages(course_packages, repos = "http://cran.rstudio.com")

data_packages <- c("covdata", "congress", "nycdogs", 
                   "ukelection2019", "uscenpops")

drat::addRepo("kjhealy")
install.packages(data_packages)
```

Installing these packages may take a little time. Once you have completed this step, you'll be ready to download the course packet and begin.

### 4. Optional step: get set up on GitHub 

GitHub is a software development platform and service that is widely used by R contributors, as well as software developers in general. You can [read some background on it from an R user's point of view here](https://happygitwithr.com/big-picture.html).

If you do not have one already, it will be useful to create a GitHub account and obtain a GitHub Personal Access Token. This is _not required_ for the course, but would be helpful to have. After you have installed R and RStudio, to get set up, read and _carefully follow_ the instructions here:

- Register a [GitHub Account](https://happygitwithr.com/github-acct.html)
- Install a [Git Client](https://happygitwithr.com/git-client.html)
- Connect to [GitHub](https://happygitwithr.com/push-pull-github.html)
- Get a [Personal Access Token](https://happygitwithr.com/credential-caching.html)

Again, setting up a GitHub account is _not required_ to fully participate in the course.


