project:
  type: website
  render:
    - "*.qmd"
    - "!slides/"
  resources:
    - "files/"
    - "projects/"
    - "slides/*.html"
    - "slides/*.pdf"
    - "slides/css/"
    - "slides/fonts/"
    - "slides/img/"
    - "slides/js"
    - "slides/libs/"
    - "slides/R/"
    - "slides/*_files/"
  preview:
    port: 27514

## Freeze seems to interact badly with the schedule.qmd / schedule.csv relation
# execute:
#   freeze: auto  # Re-render only when source changes

bibliography: files/bib/references.bib
link-citations: false
csl: files/bib/chicago-syllabus-no-bib.csl
description-meta: "Understand different ways of visualizing social science data, and how to make them with modern tools."

website:
  title: "Visualizing Social Data"
  site-url: "https://visualizingsociety.com"

  navbar:
    pinned: true
    right:
      - text: "Syllabus"
        file: syllabus/index.qmd
      - text: "Schedule"
        file: schedule/index.qmd
      - text: "Content"
        file: content/index.qmd
      - text: "Examples"
        file: example/index.qmd
      - text: "Assignments"
        file: assignment/index.qmd


  sidebar:
    - title: "Content"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Overview"
          contents:
            - content/index.qmd
        - section: "Course content"
          contents:
            - text: "01: Orientation"
              file: content/01-content.qmd
            - text: "02: Writing R"
              file: content/02-content.qmd
            - text: "03: Ways of Seeing"
              file: content/03-content.qmd

    - title: "Assignments"
      contents:
        - section: "Overview"
          contents:
            - assignment/index.qmd
        - section: "Problem sets"
          contents:
            - assignment/01-problem-set.qmd
            - assignment/02-problem-set.qmd

    - title: "Examples"
      contents:
        - section: "Overview"
          contents:
            - example/index.qmd
        - section: "Basics"
          contents:
            - text: "01: Get set up"
              file: example/01-example.qmd
            - text: "02: First steps in R"
              file: example/02-example.qmd

  page-footer:
    left: |
      Content {{< fa copyright >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
      See the [About page](/about/) page for credit information.
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

format:
  html:
    theme: html/custom.scss
    highlight-style: monokai
    toc: true
    css: html/tenso-berkeley.css

