project:
  type: website
  render:
    - "*.qmd"
    - "!projects/"
    - "!renv/"
    - "!README.qmd"
  resources:
    - "files/"
    - "projects/"
  preview:
    port: 27514

## Freeze seems to interact badly with the schedule.qmd / schedule.csv relation
freeze: auto  # Re-render only when source changes

bibliography: files/bib/references.bib
link-citations: false
csl: files/bib/chicago-syllabus-no-bib.csl
description-meta: "Understand different ways of visualizing social science data, and how to make them with modern tools."

website:
  title: "Visualizing Social Data"
  site-url: "https://visualizingsociety.com"

  navbar:
    pinned: true
    right:
      - text: "Syllabus"
        file: syllabus/index.qmd
      - text: "Schedule"
        file: schedule/index.qmd
      - text: "Content"
        file: content/index.qmd
      - text: "Examples"
        file: example/index.qmd
      - text: "Assignments"
        file: assignment/index.qmd


  sidebar:
    - title: "Content"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Overview"
          contents:
            - content/index.qmd
        - section: "Basics"
          contents:
            - text: "01: Orientation"
              file: content/01-content.qmd
            - text: "02: Writing R"
              file: content/02-content.qmd
            - text: "03: Ways of Seeing"
              file: content/03-content.qmd
            - text: "04: How ggplot Thinks"
              file: content/04-content.qmd
            - text: "05: Show the Right Numbers"
              file: content/05-content.qmd
            - text: "06: Expand your Vocabulary"
              file: content/06-content.qmd
        - section: "Applications"
          contents:
            - text: "07: Social Data and the State"
              file: content/07-content.qmd
            - text: "08: Trends and Time Series"
              file: content/08-content.qmd
            - text: "09: Maps and Spatial Data"
              file: content/09-content.qmd
            - text: "10: Iteration and Missingness"
              file: content/10-content.qmd
            - text: "11: Text as Data"
              file: content/11-content.qmd
            - text: "12: Network Data"
              file: content/12-content.qmd

    - title: "Assignments"
      contents:
        - section: "Overview"
          contents:
            - assignment/index.qmd
        - section: "Problem sets"
          contents:
            - assignment/01-problem-set.qmd
            - assignment/02-problem-set.qmd
            - assignment/03-problem-set.qmd
            - assignment/midterm.qmd
            - assignment/07-problem-set.qmd
            - assignment/08-problem-set.qmd
            - assignment/12-problem-set.qmd
            - assignment/final-project.qmd

    - title: "Examples"
      contents:
        - section: "Overview"
          contents:
            - example/index.qmd
        - section: "Basics"
          contents:
            - text: "01: Get set up"
              file: example/01-example.qmd
            - text: "02: First steps in R"
              file: example/02-example.qmd
            - text: "03: Basic Plots"
              file: example/03-example.qmd
            - text: "04: Core ggplot"
              file: example/04-example.qmd
            - text: "05: Core dplyr"
              file: example/05-example.qmd
            - text: "06: More Vocabulary"
              file: example/06-example.qmd
        - section: "Applications"
          contents:
            - text: "07: Social Data and the State"
              file: example/07-example.qmd
            - text: "08: Trends and Time"
              file: example/08-example.qmd
            - text: "09: Maps and Spatial Data"
              file: example/09-example.qmd
            - text: "12: Network Data"
              file: example/12-example.qmd
        - section: "Final Project"
          contents:
            - text: "Final Project"
              file: example/final-project-example.qmd


  page-footer:
    left: |
      Content {{< fa copyright >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
      See the [About page](/about/) page for credit information.
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

format:
  html:
    theme: html/custom.scss
    highlight-style: html/dracula-kjh.theme
    toc: true
    css: html/tenso-berkeley.css

