---
title: "2. How R and RStudio Work"
date: "2023-01-18"
---

```{r slides, echo=FALSE, include=FALSE}
source(here::here("R", "slide-things.R"))

slide_details <- tibble::tribble(
  ~youtube_id,   ~title, ~slide, ~active,
  "", "", "1", TRUE)

```

## Summary

This week we will dive into using R. We'll get oriented to the RStudio IDE and start writing code right away. At this point, there will be a lot of stuff that may seem confusing, or details that are easy to miss. Don't worry. The most important thing is to _start doing things_ in R and to _not get discouraged_ if things don't work as expected. Remember, on the one hand computing errors (and error messages) are weird and perplexing and frustrating. But on the other hand, this is mostly because computers are fast but dumb, and can only do what they are told, not what you want. This also means that when something fails, there's _always a reason_, even if it's weird or hard to track down. 

## Readings

- @wickham23:_r_data_scien, Chapters 1 and 2. 

_Note:_ This reading is fully available online at the book's website. Also, while it's listed here as a "reading" I _strongly_ recommend you work through the examples in the text as you read, typing them out as code chunks in a Quarto file and rendering them to see what happens.

## Slides

[Slides will appear here soon]
