---
title: "9. Maps and Spatial Data"
date: "2023-03-08"
---

```{r slides, echo=FALSE, include=FALSE}
source(here::here("R", "slide-things.R"))

slide_details <- tibble::tribble(
  ~youtube_id,   ~title, ~slide, ~active,
  "", "", "1", TRUE)

```

## Summary

Mapping and spatial data is a huge field all of its own. We take a look at a very tiny part of it. 

## Reading

- @wilke:2019 [Chapter 15](https://clauswilke.com/dataviz/geospatial-data.html)

## Slides

The slide decks for this week (there are three sets) are available here. 

```{r show-slide-tabs-1, echo=FALSE, results="asis"}
slide_buttons("/slides/09a-slides")
slide_tabs(slide_details, "/slides/09a-slides.html")
```



```{r show-slide-tabs-2, echo=FALSE, results="asis"}
slide_buttons("/slides/09-slides")
slide_tabs(slide_details, "/slides/09-slides.html")
```


```{r show-slide-tabs-3, echo=FALSE, results="asis"}
slide_buttons("/slides/09b-slides")
slide_tabs(slide_details, "/slides/09b-slides.html")
```



:::{.callout-tip}
**Tip**: If you type <kbd>?</kbd> (or <kbd>shift</kbd> + <kbd>/</kbd>) while going through the slides, you can see a list of special slide-specific commands.
:::
