---
title: "Problem Set 02"
author: "<PUT YOUR NAME HERE>"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
#| label = "load-libraries-data",
#| warning = FALSE,
#| message = FALSE
library(tidyverse)

gapminder <- read_csv("data/gapminder.csv")
```

# Task: Write some Markdown-formatted text and draw some plots.

## 1. Learning R and R Markdown

Replace this text with two or three sentences telling me something about yourself. Hometown, major, most recent sandwich, whatever you like. Format some of the words (even if randomly) with some bold and italic text. 

## 2. My first plots

Insert a code chunk below. You can insert it one using the menus: Code > Insert Chunk. But the keyboard shortcut is much more convenient: `Command-Option-I`. That means press the `Command`, `Option` and letter `i` keys all at once.   

Inside the chunk, create a scatterplot with the gapminder data. (Hint: like last week, use `geom_point()`.) Put (`pop`) on the x-axis, and (`gdpPercap`) on the y-axis. Color the points by `continent`.

> DELETE THIS LINE AND PUT THE FIRST CHUNK HERE

Create a new chunk below. Try creating a histogram (hint: `geom_histogram()`) of life expectancy,  by putting (`lifeExp`) on the x-axis. Do not include anything on the y-axis. (`geom_histogram()` will do that automatically for you). Experiment with the bin width. 

> DELETE THIS LINE AND PUT THE FIRST CHUNK HERE


